### ISSUE TITLE
module uses a lib   called fetch, but no package.json for it

### ISSUE THREAD

**Issue by sdetweil** [RineshRamadhin/MMM-Lastfm#2]
npm I uses package.json to load library Dependencies.  but you don't supply  one.

also, the latest version of MagicMirror require node 18 or above which have fetch built in. but may be different than how this lib works

module does not work currently

**Comment by RineshRamadhin** [comment]
Hi Sam,

Thanks for letting me know about this issue.

I have merged [a change](https://github.com/RineshRamadhin/MMM-Lastfm/pull/3) to address the `fetch` issue you raised: The external fetch library import has been removed, since the Fetch API is now natively supported.

Additionally, there is no need for a package.json file for this module, since I only uses native packages already available in the latest MagicMirror² default environment. That said, I will add a package.json in a follow up PR, to add some additional metadata.

**Comment by sdetweil** [comment]
thanks for the update.
